# your domain
domain: freedaili.cf

# database url
database_url: "https://raw.githubusercontent.com/chen2021-web/proxypool/master/config/source.yaml"

# cloudflare api
cf_email: ""
cf_key: ""

# source definition file
source-files:
  # use local file
  - source.yaml
  # use web file
  - https://raw.githubusercontent.com/chen2021-web/proxypool/master/config/source.yaml
